version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing node"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  build:
    commands:
      - echo "Build angular application"
      - ng build
      - echo "Sync with angular application"
      - npx cap sync