version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing node"
      - echo "Install node modules"
      - npm i
  build:
    commands:
      - echo "Build angular application"
      - ng build
      - echo "Sync with angular application"
      - npx cap sync